language: node_js
servers: mongodb
node_js:
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
script:
- cd backend ; npm test
cache:
  directories:
  - node_modules
env:
  global:
  - secure: Njo6KeIlDKKdu7P6Opnfh/a0yHZ6ZBaQSBO1Oa81MSY9pswgFDLu5ZjFGb3EpvJGJf5XJdGvmLDMyHkBVF5LP3nImTaYCsz12FKDXuKpybjhPjE6g3p2mNfL4Pftty+OQXAvKONvtU0XPiyX/aIvsyDmokSu2EFMXWY8CJNDBttCz7P2CJ+IQdkStCyKNPs98A/ZugNfvXgXSPyZiLenJxTMgGqBn2XMziif9hxjCF5gJ7rSaxAQFjxSgQrvpHCVXAePeYvssfnPMHUd+Nbysu9tgXzccCiBHDNNgSBzfCK6d8qVWWn8N1oH3Yu85B3D+A8YYMZBpsTgOSbTxmsqO3JD9sDKiD5h8lxfTK+0XrwiyWto+gl11NzHYurb1TJS6DS8UkI2djsSXnOSPjA6MfVGv7MNIK4IfBD1NBthc56WYljWyJaDj/Yb6fLQJqE/2/5ghzkcQLDEfc7kJeRe0+EsPWHfUuDZE/PF9Ha5KC5GnEW1NPjXROiJv9lDZVcV93kM8Tv8QmUDbn/NC1AhYm2E0aTEGJ6gOBIHY+cuSZzB8PqMHPB7/dN+W3R8LhV9M6P+SuqUiYmKyWxVwSXqGQda5HupMwD+xq8XA3+SGQ4h4VslmoTD43wGzdi76LQ3Az9EWiJzNhOhC6bcGIortAQi4xL+GZ6eN2akGi4jDAE=
  - secure: AUmaskydf4MkaVqj3ZLio3sZLQaTSPWPtS/GZBe+eJ9Ak3zDN1hr0ehcwOxJO8BjsMM9R8eDEX2UR5qDjpkxP7lk54IrRIJ83KVOzSF/TezvHMd/Phh/nsCIwhAxFEfmJJaNZSahvleg3JziIBtONuq4yLQCFtKlm0Xsip7diqiRQ3N0s+ZEmv5DI/VG59e5kiggOWb1sOmtdNP8cmCUDNfzm7R3dWhxiRphOiu8gKsZrm+ebT+2TU8wMatZKhgb6GTjn04OMhehOpa8RIYV2GFkoohkVZvQKakd5KEfOLGf1eHoFdOikICIOp8loXgz+mumrJd7v0wzXh6dADxBqnETuwAhbok09B8fIxYezO2H9sY5LdmmgIRvomCTwKQsb/ftMSvS2xS3MoI+2q2JS/RXT2NNVQH2eawPfSUQ7kJwqOsgJvgKJO2z05JntmK3bi+LTJCm2bakxKwgo0H8nlX400VcNMP5XI3cz9SogF9SzWoF9VwZ+5Xl9bmRual2AL3qHDBSiaFhaqX0eRraI7KnCG6m4682WKQzrek1K4VmoSWuv0pjxgm8O7LMa165IJrwMksqnYGNq9S55FI08jRScZfUDVD5CPSOkzkK1qpQixDFf+Bgp76oPc+VXTxVFrd3A636iv6xOK8RzaLkL+bP23sLFcuK/hCod5wTsS8=
