language: node_js
servers: mongodb
node_js:
- '12'
install:
- cd backend ; npm install
- cd backend ; npm install -dev
- cd ../frontend ; npm install
script:
- cd ..
- cd backend ; npm test
- cd ../frontend ; npm test a
cache:
  directories:
  - node_modules
env:
  global:
    secretOrKey=$secretOrKey
    Testing_URI=$Testing_URI
